# Title of the site
site_name: Gotenberg Go Client

# Description of the site
site_description: A simple Go client for interacting with a Gotenberg API. This project is a further development of the client github.com/thecodingmachine/gotenberg-go-client, which does not support the functionality of version 8.

# URL for pages editing
repo_url: https://github.com/dcaraxes/gotenberg-go-client/tree/master

# Repository name
repo_name: gotenberg-go-client

# Branch chosen when routing to repository
remote_branch: "master"

# Site content
nav:
  - Home: index.md
  - Installation: installation.md
  - Documentation:
      - Creating the client: docs/client.md
      - Working with files: docs/files.md
      - HTML to PDF: docs/htmltopdf.md
      - Read/Write EXIF metadata: docs/metadata.md
      - Making screenshots: screenshots.md

# Theme preference
theme:
  # Use `mkdocs-material`
  name: material

  # Setup lang
  language: ru

  # Used font on site
  font:
    # For ordinary text
    text: Ubuntu
    # For code pasts
    code: Monaco

  # Material coloring
  palette:
    # Use custom css-style. Check `css/custom.css`
    scheme: slate
    # Color when place the cursor on links (some kind of orange)
    accent: amber

  # Don't show target symbol nearby headers
  features:
    - header.autohide


markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.details
  - toc:
      permalink: true


# Custom css files
extra_css:
  - css/termynal.css
  - css/custom.css

# Custom js files
extra_javascript:
  - js/termynal.js
  - js/custom.js
